a2 = {
"abroad:yurtdışı",
"accept:kabul etmek",
"accident:kaza",
"adventure:macera",
"agree:anlaşmak",
"anniversary:yıl dönümü",
"ant:karınca",
"area:bölge",
"argue:tartışmak",
"arm:kol",
"backgammon:tavla",
"begin:başlamak",
"believe:inanmak",
"bell:zil",
"bite:ısırmak",
"blanket:battaniye",
"brain:beyin",
"bring:getirmek",
"business:iş",
"busy:meşgul",
"cable:kablo",
"can:yapabilme",
"cap:kep",
"cash:nakit",
"catch:yakalamak",
"chance:şans",
"changing room:soyunma odası",
"chess:satranç",
"chewing gum:sakız",
"chin:çene",
"choose:seçmek",
"climb:tırmanmak",
"cloth:kumaş",
"collect:toplamak",
"complete:tamamlamak",
"confused:şaşırmış",
"connect:bağlanmak",
"contact:temas",
"cookies:kurabiye",
"cool:sakin",
"cost:maliyet",
"cotton:pamuk",
"couch:kanepe",
"cough:öksürmek",
"crazy:çılgın",
"curious:meraklı",
"customer:müsteri",
"cut:kesmek",
"cute:sevimli",
"damage:hasar",
"dangerous:tehlikeli",
"dead:ölü",
"decide:karar vermek",
"deep:derin",
"delete:silmek",
"delicious:lezzetli",
"describe:tanımlamak",
"diamond:elmas",
"die:ölmek",
"direction:yön",
"discover:keşfetmek",
"discuss:tartışmak",
"disturb:rahatsız etmek",
"drawer:çekmece",
"dream:rüya",
"ear-ring:küpe",
"elbow:dirsek",
"elevator:asansör",
"enjoy:keyif almak",
"entertainment:eğlence",
"equal:eşit",
"escape:kaçmak",
"excellent:mükemmel",
"exhausted:bitkin",
"expensive:pahalı",
"experience:deneyim",
"explain:açıklamak",
"eyebrow:kaş",
"eyelash:kirpik",
"eyelid:göz kapağı",
"face:yüz",
"factory:fabrika",
"fail:başarısızlık",
"famous:meşhur",
"fan:hayran",
"feel:hissetmek",
"female:kadın",
"fight:dövüş",
"fill:doldurmak",
"first-aid:ilk yardım",
"flag:bayrak",
"flat:kat",
"flour:un",
"fog:sis",
"follow:takip etmek",
"food:yiyecek",
"foreign:yabancı",
"formal:resmi",
"fresh:taze",
"front:ön",
"fuel:yakıt",
"forniture:mobilya",
"future:gelecek",
"garlic:sarımsak",
"gate:kapı",
"generous:cömert",
"gift:hediye",
"glad:memnun",
"glove:eldiven",
"graduate:mezun olmak",
"grass:çimen",
"grocer:bakkal",
"grow:büyümek",
"guide:yol göstermek",
"hard:zor",
"harmful:zararlı",
"huge:kocaman",
"idea:fikir",
"impossible:imkansız",
"insect:böcek",
"intelligent:akıllı",
"introduce:takdim etmek",
"invite:davet etmek",
"island:ada",
"jam:reçel",
"jar:kavanoz",
"join:katılmak",
"joke:şaka",
"journey:seyahat",
"juice:meyve suyu",
"jump:zıplamak",
"key:anahtar",
"kick:tekme",
"kind:tür",
"knee:diz",
"knife:bıçak",
"lake:göl",
"lamb:kuzu",
"leather:deri",
"leg:bacak",
"lift:asansör",
"lip:dudak",
"lock:kilit",
"lose:kaybetmek",
"loud:gürültülü",
"lovely:sevimli",
"luck:şans",
"magic:büyü",
"mall:alışveriş merkezi",
"meat:et",
"medicine:ilaç",
"mend:tamir",
"mixed:karışmış",
"monkey:maymun",
"moon:ay",
"mountain:dağ",
"mouth:ağız",
"move:hareket",
"nail-clippers:tırnak makası",
"naughty:yaramaz",
"nervous:gergin",
"noise:gürültü",
"novel:roman",
"ocean:okyanus",
"officer:memur",
"oil:yağ",
"overweight:aşırı kilo",
"pick:pena",
"plant:bitki",
"plate:tabak",
"poem:şiir",
"point:puan",
"power:güç",
"prepare:hazırlamak",
"pretty:güzel",
"price:ücret",
"produce:üretmek",
"queen:kraliçe",
"reach:ulaşmak",
"reason:neden",
"record:rekor",
"refuse:çöp",
"relation:ilişki",
"relax:rahatlamak",
"remote control:uzaktan kumanda",
"reply:cevaplamak",
"report:rapor",
"retire:emekli olmak",
"rock:kaya",
"rope:ip",
"rude:kaba",
"rule:kural",
"safe:kasa",
"salary:maaş",
"save:kurtarmak",
"scissors:makas",
"seat:koltuk",
"select:seçmek",
"send:yollamak",
"situation:durum",
"serious:ciddi",
"serve:hizmet etmek",
"sharp:keskin",
"shine:parlamak",
"shoulder:omuz",
"shout:bağırmak",
"sign:imza atmak",
"silent:sessiz",
"simple:basit",
"ski:kayak",
"snake:yılan",
"soap:sabun",
"society:toplum",
"soft:yumuşak",
"spider:örümcek",
"stand:ayakta dikilmek",
"stone:taş",
"storm:fırtına",
"subway:metro",
"sure:emin",
"surprised:şaşırmış",
"tailor:terzi",
"taste:tat",
"team:takım",
"temperature:sıcaklık",
"tent:çadır",
"terrible:korkunç",
"throw:fırlatmak",
"tiger:kaplan",
"tissue:doku",
"tongue:dil",
"touch:dokunmak",
"transport:nakletmek",
"trouble:problem",
"try:denemek",
"usual:olağan",
"vacation:tatil",
"vacuum-cleaner:elektrik süpürgesi",
"valuable:değerli",
"vegetable:sebze",
"view:manzara",
"voice:ses",
"war:savaş",
"warm:ısıtmak",
"warning:uyarı",
"weather:hava durumu",
"wet:ıslak",
"win:kazanmak",
"wine:şarap",
"worry:endişe"
}