b1 = {
"accommodation:konaklama",
"addition:ilave",
"admire:hayran olmak",
"adopt:evlat edinmek",
"adult:yetişkin",
"advertisement:reklam",
"advice:tavsiye",
"affection:sevgi",
"afford:üstesinden gelmek",
"allow:izin vermek",
"amount:miktar",
"annual:yıllık",
"anxious:endişe",
"apologize:özür dilemek",
"appear:görünmek",
"application:uygulama",
"apply:başvurmak",
"appointment:randevu",
"army:ordu",
"arrange:planlamak",
"art:sanat",
"ashamed:utanmış",
"ashtray:kül tablası",
"attack:atak",
"attend:katılmak",
"attention:dikkat",
"attract:cezbetmek",
"average:ortalama",
"behave:davranmak",
"belief:inanç",
"belong:ait olmak",
"benefit:fayda",
"bet:bahis",
"bleed:kanamak",
"blood:kan",
"boarding time:biniş kartı",
"boarding-card:biniş kartı",
"bone:kemik",
"brake:fren",
"brand:marka",
"brief:kısa bilgi",
"bright:parlak",
"bulb:ampul",
"burglar:hırsız",
"calm:sakin",
"cancel:iptal etmek",
"certain:belirli",
"citizen:vatandaş",
"coach:koç",
"coast:kıyı",
"coin:madeni para",
"comb:taramak",
"common:yaygın",
"communicate:haberleşmek",
"compare:kıyaslamak",
"complain:şikayet etmek",
"connected flight:bağlantılı uçuş",
"consist:oluşmak",
"contain:içermek",
"convince:kandırmak",
"count:saymak",
"crime:suç",
"criticize:eleştirmek",
"curtain:perde",
"death:ölüm",
"decrease:azalma",
"defend:savunmak",
"departure gate:kalkış kapısı",
"destination:varış yeri",
"destroy:yıkmak",
"detail:detay",
"development:gelişme",
"disagree:katılmamak",
"discount:indirim",
"disease:hastalık",
"dive:dalmak",
"divide:bölmek",
"domestic flight:yurtiçi uçuş",
"drop:bırakmak",
"drug:uyuşturucu",
"dry:kuru",
"duty:görev",
"realize:farketmek",
"earthquake:deprem",
"education:eğitim",
"effort:çaba",
"elegant:zarif",
"employer:iş veren",
"engine:motor",
"environment:çevre",
"event:olay",
"excuse:affetmek",
"expect:ummak",
"explosion:patlama",
"express:ifade etmek",
"fact:olay",
"fair:adil",
"fear:korku",
"feed:beslemek",
"field:saha",
"fist:yumruk",
"fold:katlamak",
"force:güç",
"forgive:affetmek",
"funeral:cenaze",
"gentle:nazik",
"governor:vali",
"ground:zemin",
"guess:tahmin",
"guilty:suçlu",
"harbour:liman",
"hardware:donanım",
"headlight:far",
"hide:saklamak",
"hit:vurmak",
"temporary:geçici",
"hold:tutmak",
"honest:dürüst",
"hope:ummak",
"host:ev sahibi",
"humour:mizah",
"hurt:zarar vermek",
"imagine:hayal etmek",
"import:ithal etmek",
"improve:geliştirmek",
"inform:bilgi vermek",
"injection:enjeksiyon",
"ink:mürekkep",
"insist:ısrar etmek",
"interview:görüşme",
"invent:icat etmek",
"invest:yatırım yapmak",
"jealous:kıskanç",
"jewel:mücevher",
"law:yasa",
"leaf:yaprak",
"let:izin vermek",
"lie:yalan",
"liquid:sıvı",
"load:yüklemek",
"low:düşük",
"luggage:bagaj",
"measure:ölçmek",
"member:üye",
"memory:hafıza",
"military:askeri",
"mind:zihin",
"minister:bakan",
"mosque:cami",
"murder:cinayet",
"muscle:kas",
"narrow:dar",
"necessary:gerekli",
"neck:boyun",
"obey:itaat etmek",
"offer:teklif etmek",
"official:resmi",
"opinion:fikir",
"order:sipariş",
"out-of-date:tarihi geçmiş",
"owe:borçlu olmak",
"own:kendi",
"pain:ağrı",
"palace:saray",
"passenger:yolcu",
"pavement:kaldırım",
"peace:barış",
"penalty:ceza",
"perform:gösteri yapmak",
"permission:izin",
"pig:domuz",
"pill:ilaç",
"pleasant:hoş",
"plug:fiş",
"poison:zehir",
"population:nüfus",
"prefer:tercih etmek",
"pregnant:hamile",
"press:basmak",
"prime-minister:başbakan",
"private:özel",
"promise:söz vermek",
"protect:korumak",
"protest:protesto",
"provide:temin etmek",
"public:halka açık",
"publish:yayınlamak",
"punish:cezalandırmak",
"purchase:satın almak",
"purpose:amaç",
"quit:çıkmak",
"rate:oran",
"recover:iyileşmek",
"regular:düzenli",
"remind:hatırlatmak",
"remove:uzaklaştırnak",
"resign:istifa etmek",
"responsible:sorumlu",
"result:sonuç",
"root:kök",
"search:aramak",
"seatbelt:emniyer kemeri",
"secret:gizli",
"seem:görünmek",
"shoot:vurmak",
"shop-lifting:mağaza hırsızlığı",
"shut:kapamak",
"signature:imza",
"silk:ipek",
"size:boyut",
"skill:yetenek",
"skin:deri",
"sneeze:hapşırmak",
"snore:horlamak",
"socket:soket",
"soldier:asker",
"solve:çözmek",
"souvenir:hediyelik eşya",
"space:boşluk",
"spy:casus",
"staff:personel",
"stage:aşama",
"stare:dik dik bakmak",
"stationery:kırtasiyelik malzeme",
"steal:çalmak",
"steward:kabin memuru",
"stomach:karın",
"strange:garip",
"stranger:yabancı",
"sudden:ani",
"suffer:acı çekmek",
"suggest:önermek",
"support:desteklemek",
"survive:hayatta kalmak",
"tail:kuyruk",
"take off:çıkarmak",
"target:hedef",
"tiny:minik",
"tool:alet",
"trade:ticaret",
"translate:dönüştürmek",
"trip:seyahat",
"truck:kamyon",
"trust:güven",
"tyre:lastik",
"update:güncelleştirmek",
"vote:oy vermek",
"wide:geniş",
"wish:dilek",
"wonder:merak etmek"
}