b2 = {
"account:hesap",
"accounts payable:ödenecek hesap",
"accounts receivable:alacak hesap",
"accuse:suçlamak",
"achievement:başarı",
"adjust:ayarlamak",
"admit:itiraf etmek",
"advertise:reklam yapmak",
"advocate:desteklemek",
"affair:mesele",
"agreement:antlaşma",
"agriculture:tarım",
"aim:hedef",
"aisle:koridor",
"allowance:ödenek",
"ambassador:büyükelçi",
"amusement:eğlence",
"ancient:antika",
"anticipate:tahmin etmek",
"apparent:belli",
"appearance:görünüm",
"appreciate:tskdir etmek",
"appropriate:uygun",
"approve:onaylamak",
"argument:mınakaşa",
"arrest:tutuklamak",
"audience:dinleyici",
"avoid:kaçınmak",
"baggage-claim:bagaj teslim yeri",
"balance sheet:bilanço",
"bank-account:banka hesabı",
"bankrupt:iflas etmek",
"bargain:pazarlık etmek",
"beg:dilenmek",
"beggar:dilenci",
"blame:suçlamak",
"board of directors:yönetim kurulu",
"breath:nefes",
"bribe:rüşvet",
"budget:bütçe",
"candidate:aday",
"capital:başkent",
"cash flow:nakit akışı",
"cemetery:mezarlık",
"Chamber of Commerce:ticaret odası",
"charge:şarj",
"charming:büyüleyici",
"Chief Executive:başkan",
"circumstance:durum",
"claim:iddia etmek",
"clerk:katip",
"client:müşteri",
"coal:kömür",
"comment:yorum",
"commerce:ticaret",
"commercial:ticari",
"community:topluluk",
"competition:rekabet",
"complaint:şikayet",
"concentrate:konsantre olmak",
"condition:durum",
"confess:itiraf etmek",
"congratulate:tebrik etmek",
"congress:kongre",
"consider:düşünmek",
"construction:inşaat",
"consult:danışmak",
"contest:yarışma",
"contribute:katkıda bulunmak",
"convert:dönüştürmek",
"court:mahkeme",
"crossword:bulmaca",
"cruel:zalim",
"customs:gümrük",
"dashboard:gösterge paneli",
"deadline:son tarih",
"deceive:aldatmak",
"declare:bildirmek",
"define:tanımlamak",
"deflation:deflasyon",
"depend:bağlı olmak",
"desire:arzu",
"devaluation:devalüasyon",
"diagnose:teşhis koymak",
"disappear: kaybolmak",
"disappoint:hayal kırıklılığına uğratmak",
"distance:mesafe",
"distribution:dağıtım",
"dreadful:korkunç",
"eager:istekli",
"election:seçim",
"embassy:elçilik",
"encourage:cesaret etmek",
"enemy:düşman",
"enterprise:kuruluş",
"entrepreneur:girişimci",
"envy:imrenmek",
"essay:kompozisyon",
"establish:kurmak",
"estimate:tahmin etmek",
"evaluate:değerlendirmek",
"evidence:kanıt",
"exaggerate: abartmak",
"examine:incelemek",
"exchange-rate:döviz kuru",
"exhibition:sevgi",
"experiment:deney",
"fame:ün",
"fence:çit",
"fix:tamir etmek",
"fluent:akıcı",
"foolish:aptal",
"forecast:tahmin",
"fragile:kırılgan",
"frame:çerçeve",
"franchise:imtiyaz",
"frequent:sık sık",
"fund raising:fon artışı",
"gamble:kumar oynamak",
"gear/transmission:vites",
"globalization:küreselleşme",
"government:hükümet",
"grateful:minnertar",
"growth rate:büyüme oranı",
"hair-dryer: saç kurutma makinesi",
"harvest:hasat",
"hesitate:tereddüt etmek",
"hire:kiralamak",
"hitch-hike:otostop çekmek",
"homesick:vatan hasreti çeken",
"identification:kimlik",
"in advance:önceden",
"include:içermek",
"income:gelir",
"increase:artmak",
"independent:bağımsız",
"inflation:enflasyon",
"innocent:masum",
"inspection:teftiş",
"inspector:müfettiş",
"insurance:sigorta",
"interest-rate:faiz oranı",
"invoice:fatura",
"judge:yargıç",
"justice:adalet",
"kidnapping: kaçırmak",
"knowledge:bilgi",
"labor force:işgücü",
"landlord:kiraya veren",
"licence-plate:araba plakası",
"life-vest:can yeleği",
"loan:borç",
"loan agreement:kredi anlaşması",
"magnificent:muhteşem",
"maintain:sürdürmek",
"market share:pazar payı",
"marketing research:pazarlama araştırması",
"marvellous:fevkalade",
"massive:masif",
"member of parliemant:milletvekili",
"mention:bahsetmek",
"merchandise:mal",
"nation:ulus",
"net capital:net sermaye",
"objective:objektif",
"observe:gözlemlemek",
"obvious:bariz",
"opportunity:fırsat",
"participate:katılmak",
"patience:sabır",
"percentage:yüzde",
"persuade:ikna etmek",
"pollution:kirlilik",
"postpone:ertelemek",
"president:başkan",
"price control:fiyat kontrolü",
"prison:hapishane",
"process:süreç",
"profit:kar",
"prohibit:yasaklamak",
"promotion:promosyon",
"property:özellik",
"proposal:teklif",
"prove:kanıtlamak",
"publicity:tanıtım",
"punctual:dakik",
"punishment:ceza",
"quantity:miktar",
"quarrel:kavga",
"queue:sıra",
"receipt:fiş",
"recieve:teslim almak",
"recognize:tanımak",
"recommend:tavsiye vermek",
"reduce:azaltmak",
"rub:ovmak",
"schedule:takvim",
"regret:pişmanlık",
"reject:reddetmek",
"release:serbest bırakmak",
"religion:din",
"reluctant:isteksiz",
"rely:güvenmek",
"represent:temsil etmek",
"request:istek",
"resolution:çözüm",
"resource:kaynak",
"respect:saygı",
"respond:cevap vermek",
"revenue:gelir",
"revise:tekrar düzeltme yapmak",
"sand:kum",
"science:bilim",
"seek:aramak",
"sense:duyu",
"shake:sallamak",
"share:paylaşmak",
"sink:batmak",
"skyscraper:gökdelen",
"steering-wheel:direksiyon",
"strike:vuruş",
"substitute:yerine geçmek",
"supplier:tedarikçi",
"suppose:varsaymak",
"swear:yemin etmek",
"take action:harekete geçmek",
"take advantage:avantaj elde etmek",
"task:görev",
"tax:vergi",
"throat:boğaz",
"to book:ayırtmak",
"torture:işkence",
"trademark:marka",
"transmit:iletmek",
"treat:tedavi etmek",
"treatment:tedavi",
"trick:hile",
"underline:altını çizmek",
"unemployment:işsizlik",
"urgent:acil",
"VAT (Value Added Tax):katma değer vergisi",
"violent:şiddetli",
"volunteer:gönüllü",
"warehouse:depo",
"wealthy:varlıklı",
"weapon:silah",
"whistle:ıslık",
"wholesale:depo",
"witness:tanık",
"zip:fermuar"
}