c1 = {
"abstract:soyutlamak",
"abuse:taciz",
"accordance:uyum",
"accurate:kesin",
"acknowledge:kabullenmek",
"acquire:elde etmek",
"acquisition:kazanma",
"adequate:yeterli",
"adjacent:bitişik",
"allocate:tahsis etmek",
"ally:müttefik",
"antibody:antikor",
"arch:kemer",
"arrangement:ayarlama",
"array:dizi",
"artificial:yapay",
"assess:değerlendirmek",
"asset:varlık",
"associate:ortak",
"assume:farz etmek",
"assure:garanti etmek",
"attribute:özellik",
"auction:açık arttırma",
"audit:denetim",
"beam:ışın",
"binary:ikili",
"boost:arttırmak",
"breach:ihlal",
"capture:tutsak etmek",
"cease:durdurmak",
"chorus:koro",
"cluster:küme",
"colleague:iş arkadaşı",
"commit:işlemek",
"commodity:emtia",
"compensation:tazminat",
"comply:uymak",
"component:bileşen",
"compound:birleştirmek",
"comprise:içermek",
"conceive:gebe kalmak",
"concerning:ilişkin",
"conduct:yönetmek",
"confine:sınırlamak",
"confirm:onaylamak",
"conflict:fikir ayrılığı",
"confront:konfor",
"conjunction:bağlaç",
"consequence:sonuç",
"conversation:koruma",
"consist of:oluşmak",
"consonant:ünsüz",
"constant:sabit",
"constitute:oluşturmak",
"constraint:kısıtlama",
"context:bağlam",
"contraction:kasılma",
"contractor:müteahhit",
"contrasting:zıt",
"contribution:katkı",
"convey:iletmek",
"criticism:eleştiri",
"crucial:kritik",
"curb v.:frenlemek",
"curve:eğri",
"damp:nemli",
"debtor:borçlu",
"debut:çıkış",
"decade:onyıl",
"decay:çürümek",
"decline:reddetmek",
"dedicate:adamak",
"deficit:açık",
"deliberate:kasten",
"delicate:narin",
"density:yoğunluk",
"depict:göstermek",
"depreciation:amortisman",
"derivative:türev",
"disapprove:onaylamamak",
"discharge:deşarj",
"discourse:söylem",
"dismiss:azletmek",
"disposal:imha etmek",
"dispute:anlaşmazlık",
"dissolve:çözmek",
"distant:mesafe",
"distinct:belirgin",
"distinguish:ayırt etmek",
"domestic:yerel",
"dominate:hakim olmak",
"due:vadesi dolmuş",
"efficient:verimli",
"elaborate:detaylandırmak",
"elect:seçmek",
"embrace:kucaklamak",
"emerge:ortaya çıkmak",
"encounter:rastlamak",
"engage:angaje etmek",
"enhance:genişletmek",
"enquiry:soruşturma",
"ensure:sağlamak",
"equilibrium:denge",
"equity:eşitlik",
"equivalent:eşdeğer",
"essential:gerekli",
"evolve:evrim geçirmek",
"exceed:aşmak",
"exemption:muafiyet",
"expand:genişletmek",
"expense:masraf",
"exploit:faydalanmak",
"exploration:keşif",
"expode:açığa çıkarmak",
"expose:ortaya çıkarmak",
"extend:uzatmak",
"extract:çıkarmak",
"faintly:hafiften",
"faucet:musluk",
"fiscal:mali",
"fraction:kesir",
"framework:çerçeve",
"fundamental:temel",
"gain:kazanç",
"generate:üretmek",
"genre n.:tür",
"genuine:eşsiz",
"gesture:jest",
"gradual:kademeli",
"grain:tahıl",
"gravitational:yerçekimsel",
"highlight:vurgulamak",
"imperative:zorunlu",
"implement v.:uygulamak",
"implication:olası sonuç",
"impose:empoze etmek",
"improvement:gelişme",
"incentive:teşvik",
"incidence:insidans",
"incur:maruz kalmak",
"indicate:belirtmek",
"induce:teşvik etmek",
"initial:ilk",
"initiative:girişim",
"interim:geçici",
"interior:iç mekan",
"interpret:yorumlamak",
"interrupt:kesmek",
"interval:aralık",
"intervention:araya girmek",
"irritate:kızdırmak",
"justify:savunmak",
"keen:hevesli",
"lean:yağsız",
"leap:sıçramak",
"linguistic:dil bilimi",
"loose:gevşetmek",
"lump:yumru",
"magnitude:büyüklük",
"mainstream:ana akım",
"majority:çoğunluk",
"manner:tavır",
"marine:deniz",
"membrane:zar",
"minority:azınlık",
"monetary:parasal",
"movement:hareket",
"narrative:anlatı",
"narrator:dış ses",
"noticeable:farkedilebilir",
"obscure:belirsiz",
"obtain:elde etmek",
"occasion:fırsat",
"occupy:işgal etmek",
"occur:meydana gelmek",
"opponent:rakip",
"oppose:karşı çıkmak",
"ordinal:sıralı",
"outline:anahat",
"particularly:özellikle",
"pension:emeklilik",
"permanent:kalıcı",
"permit:izin vermek",
"possess:elinde bulundurmak",
"praise:övmek",
"precede:önce",
"precise:kesin",
"predator:yırtıcı",
"predict:tatmin etmek",
"premises:tesis",
"prescribe:reçete yazmak",
"preserve:korumak",
"presumably:muhtemelen",
"prevent:önlemek",
"primary:öncelik",
"primitive:ilkel",
"probe:incelemek",
"prompt:çabuk",
"prospect:olasılık",
"rapid:hızlı",
"recall:geri çağırma",
"reckon:hesaba katmak",
"recognition:tanıma",
"recruit:iyileştirmek",
"redundancy:fazlalık",
"relevant:ile ilgili",
"remark:açıklamak",
"remote:uzak",
"replacement:yenisiyle değiştirme",
"resemble:benzemek",
"residue:kalıntı",
"respective:saygılı",
"estrict:kısıtlamak",
"retain:sürdürmek",
"reveal:ortaya çıkartmak",
"reverse:tersi",
"revise:tekrar düzeltme yapmak",
"revival:canlanmak",
"rival:rakip",
"savage:vahşi",
"scatter:saçılma",
"sediment:tortu",
"sequence:sekans",
"severe:şiddetli",
"sheer:sırf",
"slope:eğim",
"solvent:çözücü",
"specimen:numune",
"statutory:yasal",
"steer:yönlendirmek",
"stem:kök",
"stimulate:canlandırmak",
"strain:gerginlik",
"subsequent:sonraki",
"subsidiary:yan kuruluş",
"substantial:varlıklı",
"subtle:hemen göze çarpmayan",
"suffix:sonek",
"sustain:güç vermek",
"tender:sunmak",
"undergo:uğramak",
"underlie:altında yatan",
"undertake:üstlenmek",
"vast:büyüklük",
"vegetation:bitki örtüsü",
"velocity:hız",
"venture:girişim",
"verse:ayet",
"withdraw:geri çekmek",
"yield:teslim olmak"
}